#ifndef QTCQTESTPLUGIN_GLOBAL_H
#define QTCQTESTPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(QTC_QTEST_LIBRARY)
#  define QTC_QTEST_PLUGIN_SHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTC_QTEST_PLUGIN_SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCQTESTPLUGIN_GLOBAL_H

